.PHONY: test

CFLAGS= -I ../src -Wall -g -DSENTINEL
# CPPFLAGS := -I ../src

test: test-rbtree
	./test-rbtree
	valgrind ./test-rbtree

test-rbtree: test-rbtree.o ../src/rbtree.o

../src/rbtree.o:
	$(MAKE) -C ../src rbtree.o

clean:
	rm -f test-rbtree *.o
